version: '3'
services:
  frontend:
    build:
      context: ./frontend-angular
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend-node
    ports:
      - "3000:3000"
